### ISSUE TITLE
Debug Fixes

### ISSUE THREAD

**Issue by llee454** [sifive/ProcKami#106]
- rename the debug_command register "debug_executing"
- replace the context value (1) used by the debug CSRs with 0.
  - context codes are arbitrary for the debug interface CSRs - set them to 0
- replace array index notions in debug_states_all, etc with ArrayConst calls
- add an implicit ebreak region after the program buffer in DebugDevice.v and remove the ebreaks initialized into the program buffer.
- make the CsrFieldValue an inductive type rather than use sums.
- the cmderr register is being set to magic number 1 as a side effect of writes to the command CSR by the debug driver, which is an ambiguous code value
- modify csrFieldAny so that that automatically adds the @^ prefix and doesn't require the field name to have it.
- fix the command CSR entry so that it sets busy to true and cmderr to 0
- modify the debug_hart_halt function so that it clears the halt request
- modify the debug_hart_resume function so that it clears the resume request
- ask whether or not we should be able to select more than one hart when executing an abstract command.

**Comment by vmurali** [comment]
https://github.com/sifive/ProcKami/commit/7108a76565af947772d0acc4801dd259e6d00ac3
