### ISSUE TITLE
CSR fields bug

### ISSUE THREAD

**Issue by vmurali** [sifive/ProcKami#47]
Currently different views have different types for registers, and nobody is checking if the reads are correct. Here's the proposed solution:

- Each CSR group has a single CSRField that contains:
  Record CSRField
    := {
         csrFieldName : string;
         csrFieldKind : Kind;
         csrFieldIsValid
           : FieldUpd @# ty ->
             csrFieldKind @# ty ->
             csrFieldKind @# ty ->
             Bool @# ty;
         csrFieldXform
           : FieldUpd @# ty ->
             csrFieldKind @# ty ->
             csrFieldKind @# ty ->
             csrFieldKind @# ty
      }.
Let the Kami struct formed from a list of above fields be called csrKind.
(Note that there's no "csrFieldDefaultValue").
It also has a csrAddr, list csrViews and csrAccess.
- Each csrView contains two simple transformations csrKind -> CsrValue and CsrValue -> csrKind, where CsrValue is of Xlen length. If the dynamic size of the view is x bits, while CsrValue is Bit y, you simply unpack \compose ZeroExtendTruncLsb to transform a CsrValue into csrKind. But, the Alternative way requires you to perform the right transformation from csrKind to CsrValue. For instance, if the csrKind holds an address, you want to sign-extend that to form the CsrValue. If it holds something other than an address, perhaps, you want to zero-extend. So this is determined on a case-by-case basis.

**Comment by llee454** [comment]
746a4288
