### ISSUE TITLE
Change the Processor Core so that the Reg Writer Reads CSR Values Before CSR Writes Rather than the Register Reader Task

### ISSUE THREAD

**Issue by llee454** [sifive/ProcKami#7]

**Comment by llee454** [comment]
The CSR functional unit (Zicsr.v) requires the CSR value to compute the new CSR value. The new CSR value is computed based on the input register/immediate value, and a variable mask. Originally, I thought that I could simply pass mask that needs to be applied to the register writer, but different instructions apply the mask to different values (register/immediate values). In general to compute the result of a CSR instruction I need three datums: the original CSR value, the mask to apply, and the value to apply the mask to (original csr value, or immediate value).

**Comment by vmurali** [comment]
I believe the comment is not valid anymore.

Zicsr must be a special functional unit that is executed only in the final stage. It should be treated as a special function, just like memory.
