### ISSUE TITLE
Make misaligned exception have priority over page fault as default

### ISSUE THREAD

**Issue by vmurali** [sifive/ProcKami#93]

**Comment by llee454** [comment]
Add parameter flag called allowMisaligned. When this flag is false, throw a misaligned access exception as soon as the PC is found to be misaligned irregardless of the device support.

**Comment by llee454** [comment]
PC, and all other memory addresses.

**Comment by llee454** [comment]
isAligned _ n, n = 0 byte aligned, 1 = 16 bit alinged, 2 = 32 bit aligned.

**Comment by llee454** [comment]
https://github.com/sifive/ProcKami/commit/d2790a6246b4e3144d381bed93568286329283c2
